### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by fabaff** [sirl1on/python-pocketcasts#3]
Using the module seems no longer be possible.

```bash
>>> import pocketcasts as pc
>>> api = pc.Api('the_username', 'the_passwrod')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fab/Documents/repos/ha/home-assistant/lib64/python3.6/site-packages/pocketcasts/api.py", line 18, in __init__
    response.raise_for_status()
  File "/home/fab/Documents/repos/ha/home-assistant/lib64/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://play.pocketcasts.com/users/sign_in
```

**Comment by fabaff** [comment]
Reported at https://github.com/home-assistant/home-assistant/issues/16103

**Comment by zackbcom** [comment]
Looks like they have swapped to "https://api.pocketcasts.com/user/login" instead of "https://play.pocketcasts.com/users/sign_in"

**Comment by zackbcom** [comment]
I'm able to leverage the new API. I will see if I can make a fork and get it updated.

**Comment by daltschu22** [comment]
The fork works great, thanks so much! :)

**Comment by daltschu22** [comment]
Spoke too soon! Broken for a few things, such as search:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://play.pocketcasts.com/web/podcasts/search.json`

**Comment by zackbcom** [comment]
I'll take a look at it this week. Sorry, been super busy!

**Comment by daltschu22** [comment]
I got it work using a POST

```
        params = {'term': search}
        response = self._session.post(
            "https://api.pocketcasts.com/discover/search",
            headers=self._api_header,
            data=params
            )
        response.raise_for_status()

        podcasts = []
        for podcast_json in response.json()['podcasts']:
            podcasts.append(podcast_json)

        return podcasts
```
